# Generated by Django 3.1.7 on 2021-04-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadditives', '0002_eadditives_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eadditives',
            name='additive_type',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='eadditives',
            name='harmfulness',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='eadditives',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
