# Generated by Django 3.1.7 on 2021-04-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadditives', '0003_auto_20210420_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eadditives',
            name='additive_type',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='eadditives',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eadditives',
            name='harmfulness',
            field=models.CharField(max_length=50),
        ),
    ]
