# Generated by Django 3.1.7 on 2021-04-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadditives', '0004_auto_20210420_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eadditives',
            name='harmfulness',
            field=models.CharField(max_length=300),
        ),
    ]
