# Generated by Django 3.1.7 on 2021-04-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadditives', '0005_auto_20210420_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eadditives',
            name='additive_type',
            field=models.CharField(choices=[('Food colours', 'Colours'), ('Preservatives', 'Preservatives'), ('Antioxidants', 'Antioxidants'), ('Thickeners, emulsifiers and stabilisers', 'Thickeners'), ('Acidity regulators, anti-caking agents', 'Acidity Regulators'), ('Sweeteners, foaming agents and gases', 'Sweeteners')], default='Food colours', max_length=300),
        ),
        migrations.AlterField(
            model_name='eadditives',
            name='harmfulness',
            field=models.CharField(choices=[('Safe', 'Safe'), ('Potentially dangerous', 'Potentially Dangerous'), ('Dangerous', 'Dangerous'), ('No information about the harmfulness of this additive yet', 'No Info')], default='No information about the harmfulness of this additive yet', max_length=300),
        ),
    ]
