# Generated by Django 3.1.7 on 2021-05-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadditives', '0006_auto_20210421_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eadditives',
            name='additive_type',
            field=models.CharField(choices=[('COLOURS', 'Food colours'), ('PRESERVATIVES', 'Preservatives'), ('ANTIOXIDANTS', 'Antioxidants'), ('THICKENERS', 'Thickeners, emulsifiers and stabilisers'), ('ACIDITY_REGULATORS', 'Acidity regulators, anti-caking agents'), ('FLAVOUR_ENHANCERS', 'Flavour enhancers'), ('SWEETENERS', 'Sweeteners, foaming agents and gases'), ('ADDITIONAL_CHEMICALS', 'Additional Chemicals'), ('NO_TYPE', 'No type provided for this additive yet')], default='NO_TYPE', max_length=30),
        ),
        migrations.AlterField(
            model_name='eadditives',
            name='harmfulness',
            field=models.CharField(choices=[('SAFE', 'Safe'), ('POTENTIALLY_DANGEROUS', 'Potentially dangerous'), ('DANGEROUS', 'Dangerous'), ('NO_INFO', 'No information about the harmfulness of this additive yet')], default='NO_INFO', max_length=30),
        ),
    ]
